docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "2022-2.0-py37-tiled"
conda_env_file: "2022-2.0-py37-tiled-env.yml"
conda_binary: "mamba"
python_version: "3.7"
pkg_name: ""
pkg_version: ""
# extra_packages: "nsls2-collection=2021C2.0=*_0 tmate mamba"
extra_packages: "tmate mamba"
channels: "-c conda-forge"
#extra_cmd_before_install: "yum install mesa-libGL mesa-libGL-devel -y"
extra_cmd_before_install: "yum install mesa-libGL -y"
extra_cmd_after_install: "conda remove perl --force -y"
docker_upload:
  - ghcr
  - dockerhub
  # - quay
zenodo_upload: "no"
zenodo_metadata:
  metadata:
    title: "NSLS-II collection conda environment"
    upload_type: "software"
    description: "NSLS-II collection conda environment"
    version: 2022-2.0
    creators:
      - name: Rakitin, Maksim
        affiliation: "Brookhaven National Laboratory"
      - name: Bischof, Garrett
        affiliation: "Brookhaven National Laboratory"
