docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "tomviz-{{ today }}"
conda_binary: "mamba"
python_version: "3.7"
pkg_name: "tomviz"
# pkg_version: "1.10.0.post196"
pkg_version: "1.10.0.post156"
extra_packages: "databroker area-detector-handlers tomopy pyxrf"
extra_cmd_after_install: "pip install itk-elastix tiled[client]==0.1.0a53 databroker[client]==2.0.0a22; conda list"
channels: "-c conda-forge"
